### ISSUE TITLE
No apple tv found

### ISSUE THREAD

**Issue by djacobs23** [lukasroegner/homebridge-apple-tv-remote#43] opened 2020-05-14 13:51 UTC
I have tried using your plugin and the appletv-x to get the codes and it finds no appletvs. I have 8 of them. The developer of Appletv-x is not much help. Do you have any hints on how to discover my Apple TVs from my Raspberry Homebridge setup?

**Comment by lukasroegner** [comment] 2020-05-15 07:45
@djacobs23 I would suggest to check your network configuration first.
- Do you have a firewall that prevents the Raspberry to communicate with the Apple TVs?
- Are the Apple TVs on the same network as the Raspberry?
- Are you running a VPN on the Raspberry?

I would recommend to create a static lease (i.e. static IP address) for the Apple TV(s) you want to use with the plugin. You can do a `ping` to the Apple TV(s) to check whether they are reachable from the Raspberry.

**Comment by djacobs23** [comment] 2020-05-15 08:41
I should have provided you all the info that you mentioned. All of my Apple TVs have reserved IP addresses. As does my rPi. I can ping them from the Pi without issue. I am running the out of the box Homebridge installer for the rPi so I do not believe there is a VPN.

**Comment by lukasroegner** [comment] 2020-05-15 15:35
What you can also try:
- Install `node-appletv-x` on a different device and check whether you get results there
- Check your node version (I'm running the `appletv` command successfully on v10 and v12)
- Try `appletv pair --verbose`, maybe you get any error messages

Which Apple TV models do you own? I have two Apple TV 4K running the latest update. Both can be found via `appletv pair`.

**Comment by djacobs23** [comment] 2020-05-15 16:27
I hav installed it on my mac. The version is 14.2.0

Appletv-x version is 1.0.16

I now get 2 of my Apple tv’s to show up, but still not the other 6?

This is so flaky. 

Thanks,

Doug Jacobs
513-739-9471

**Comment by lukasroegner** [comment] 2020-05-15 16:52
Here is another thing you can try:

```
appletv pair --timeout 60
```

This increases the scan timeout to 60 seconds.

**Comment by djacobs23** [comment] 2020-05-15 20:43
I have tried that as well

but here is what I found. The two apple Tis I can see are the only two on wireless. On my Orbing. The rest are hardwired to my netgear Switch.

I am thinking some config between my orbing set up and my switch is causing the packets to be blocked. I can ping the devices, but something is blocking the appletv pair command.

Thanks,

Doug Jacobs
513-739-9471

**Comment by lukasroegner** [comment] 2020-05-16 09:44
> I am thinking some config between my orbing set up and my switch is causing the packets to be blocked. I can ping the devices, but something is blocking the appletv pair command.

Yes, that sounds like the cause of the issue. I'm closing this issue for now, feel free to reopen if issues occur after you fixed the network-related stuff.

**Closed by lukasroegner** 2020-05-16 09:44 UTC
